set_property IOSTANDARD LVCMOS33 [get_ports buzzer_out]
set_property PACKAGE_PIN G13 [get_ports buzzer_out]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN T5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property PACKAGE_PIN P15 [get_ports rst]
