# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/source/display_vga.xdc

# IP: ip/logo_rom_2/logo_rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==logo_rom || ORIG_REF_NAME==logo_rom} -quiet] -quiet

# IP: ip/dcm_25m_2/dcm_25m.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dcm_25m || ORIG_REF_NAME==dcm_25m} -quiet] -quiet
